import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, CheckCircle2, FileSearch, GitBranch, Sparkles } from "lucide-react";
import { GraphVisualization, PageShell, SampleNotice, SectionLabel, SourceViewer } from "@/components/lab";
import { evidence, evidenceDiscoveries } from "@/lib/demo-data";

export const Route = createFileRoute("/evidence")({ head: () => ({ meta: [
  { title: "Evidence Explorer | RAGNEX" }, { name: "description", content: "Explore sample sources, entity relationships, and investigation history in RAGNEX." },
  { property: "og:title", content: "RAGNEX Evidence Explorer" }, { property: "og:description", content: "Inspect sources, relationships, and investigation actions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: EvidencePage });

function EvidencePage() { return <PageShell><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><SectionLabel>RAGNEX · Evidence · Verification</SectionLabel><h1 className="text-3xl font-semibold md:text-5xl">Explore the evidence</h1><p className="mt-3 text-sm text-muted-foreground">Inspect the source text, entities, relationships, and supporting evidence behind the demo answer.</p></div><SampleNotice>Simulation Mode · 4 demo sources</SampleNotice></div><div className="grid gap-5 xl:grid-cols-[minmax(0,.75fr)_minmax(0,1.25fr)]"><section className="panel min-w-0 p-5"><div className="mb-5 flex items-center gap-2"><FileSearch className="size-4 text-primary" /><h2 className="font-semibold text-foreground">Source Documents & Snippets</h2></div><SourceViewer /></section><div className="min-w-0 space-y-5"><section className="panel min-w-0 p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><GitBranch className="size-4 text-primary" /><h2 className="font-semibold text-foreground">Entities & Relationships</h2></div><div className="flex gap-3 text-[10px] text-muted-foreground"><span>● People</span><span className="text-violet">● Companies</span><span className="text-cyan">● Products</span></div></div><GraphVisualization /></section><section className="panel min-w-0 p-5"><div className="mb-5 flex items-center gap-2"><CalendarDays className="size-4 text-primary" /><h2 className="font-semibold text-foreground">Evidence Timeline</h2></div><div className="relative grid gap-4 border-l border-border pl-5 md:grid-cols-2">{evidence.map((item) => <article key={item.title} className="relative min-w-0 bg-secondary p-4 before:absolute before:-left-[23px] before:top-5 before:size-1.5 before:bg-primary"><span className="text-[10px] font-medium text-cyan">{item.date}</span><h3 className="mt-1 text-sm font-medium text-foreground">{item.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.excerpt}</p></article>)}</div></section></div></div>
  <section className="mt-6 panel p-5 md:p-6"><div className="mb-6 flex items-center gap-2"><CheckCircle2 className="size-4 text-cyan" /><h2 className="font-semibold text-foreground">Agentic Evidence Discovery</h2></div><div className="grid gap-3 md:grid-cols-2">{evidenceDiscoveries.map((item, index) => <article key={item.step} className="border border-border bg-secondary p-5"><div className="flex items-start justify-between gap-3"><span className="text-xs font-semibold text-primary">STEP 0{index + 1} · {item.step}</span><span className="text-[10px] font-semibold uppercase text-cyan">{item.status}</span></div><h3 className="mt-3 text-sm font-semibold text-foreground">{item.evidence}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground"><strong className="text-foreground">Why useful:</strong> {item.why}</p></article>)}</div></section>
  <section className="mt-6 panel p-5 md:p-6"><div className="mb-6 flex items-center gap-2"><Sparkles className="size-4 text-primary" /><h2 className="font-semibold">Investigation History</h2></div><div className="grid gap-px border border-border bg-border lg:grid-cols-4">{[["Vector search performed","Initial semantic retrieval","Insufficient evidence"],["Graph traversal selected","Resolve acquisition relationship","New relationship discovered"],["Targeted retrieval performed","Close strategy timing gap","Leadership interview found"],["Evidence evaluation completed","Test corroboration","Evidence sufficient"]].map(([action,why,result],index) => <article key={action} className="bg-background p-5"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-semibold text-primary">0{index+1}</span>{index < 3 && <ArrowRight className="size-3 text-muted-foreground" />}</div><h3 className="text-sm font-medium">{action}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">Why: {why}</p><p className="mt-2 text-xs leading-5 text-cyan">Result: {result}</p></article>)}</div></section></PageShell>; }