import { createFileRoute } from "@tanstack/react-router";
import { Activity, Clock3, Coins, Crosshair, ShieldCheck } from "lucide-react";
import { BenchmarkChart, MetricCard, PageShell, SampleNotice, SectionLabel } from "@/components/lab";
import { benchmark, complexityData } from "@/lib/demo-data";

export const Route = createFileRoute("/metrics")({ head: () => ({ meta: [
  { title: "Benchmark Performance | RAGNEX" }, { name: "description", content: "Explore sample RAG, GraphRAG, and Agentic GraphRAG performance tradeoffs in RAGNEX." },
  { property: "og:title", content: "RAGNEX Benchmark Performance" }, { property: "og:description", content: "Sample benchmark data across AI research approaches." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: MetricsPage });

function MetricsPage() { return <PageShell><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><SectionLabel>RAGNEX · Metrics · Demo benchmark</SectionLabel><h1 className="text-3xl font-semibold md:text-5xl">Benchmark Performance</h1></div><SampleNotice>Simulation Mode · Demo Data</SampleNotice></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Accuracy" value="92%" detail="Agentic · complex set" icon={<Crosshair className="size-4" />} /><MetricCard label="Completeness" value="94%" detail="Best sample coverage" icon={<ShieldCheck className="size-4" />} /><MetricCard label="Token efficiency" value="94%" detail="RAG · lower token cost" icon={<Coins className="size-4" />} /><MetricCard label="Fastest latency" value="1.8s" detail="RAG · simulated run" icon={<Clock3 className="size-4" />} /><MetricCard label="Evidence quality" value="93%" detail="Agentic · cited claims" icon={<Activity className="size-4" />} /></section>
  <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{([...[ ["Accuracy","accuracy",undefined], ["Completeness","completeness",undefined], ["Token Efficiency","tokenEfficiency",undefined], ["Latency","latency","s"], ["Evidence Quality","evidence",undefined] ]] as const).map(([title,metric,suffix]) => <article key={metric} className="panel p-5"><h2 className="mb-1 font-semibold text-foreground">{title}</h2><p className="mb-6 text-xs text-muted-foreground">{metric === "latency" ? "Lower is faster" : "Higher is better"}</p>{suffix ? <BenchmarkChart data={benchmark} metric={metric} height={175} suffix={suffix} /> : <BenchmarkChart data={benchmark} metric={metric} height={175} />}</article>)}</section>
  <section className="mt-6 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><article className="panel overflow-hidden p-6"><h2 className="text-xl font-semibold">Performance by Question Complexity</h2><p className="mt-1 text-xs text-muted-foreground">Accuracy across representative question types</p><div className="mt-7 space-y-6">{complexityData.map((row) => <div key={row.label} className="grid gap-3 md:grid-cols-[120px_1fr]"><span className="text-xs font-medium text-foreground">{row.label}</span><div className="grid gap-2"><ComplexityBar label="RAG" value={row.rag} kind="cyan" /><ComplexityBar label="Graph" value={row.graph} kind="violet" /><ComplexityBar label="Agentic" value={row.agentic} kind="primary" /></div></div>)}</div></article><article className="panel p-6"><h2 className="text-xl font-semibold">Accuracy vs Token Cost</h2><p className="mt-1 text-xs text-muted-foreground">Tradeoff view</p><div className="relative mt-8 h-72 border-b border-l border-border" role="img" aria-label="Scatter plot of accuracy versus token cost"><span className="absolute -left-5 top-1/2 -rotate-90 text-[10px] text-muted-foreground">Accuracy</span><span className="absolute bottom-[-26px] left-1/2 text-[10px] text-muted-foreground">Token cost →</span>{[{x:30,y:43,l:"RAG",c:"bg-cyan"},{x:58,y:22,l:"GraphRAG",c:"bg-violet"},{x:82,y:10,l:"Agentic",c:"bg-primary"}].map((point) => <div key={point.l} className="absolute" style={{left:`${point.x}%`,top:`${point.y}%`}}><span className={`block size-4 ${point.c} shadow-glow`} /><span className="mt-1 block -translate-x-1/3 text-[10px] text-muted-foreground">{point.l}</span></div>)}</div></article></section>
  <section className="mt-14"><SectionLabel>Decision guide</SectionLabel><h2 className="text-2xl font-semibold">When Does Agentic Reasoning Help?</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-foreground">Agentic GraphRAG is valuable when questions require multi-hop investigation, evidence evaluation, or adaptive retrieval.</p><div className="mt-5 grid gap-px border border-border bg-border md:grid-cols-4">{[["Simple questions","RAG may be sufficient"],["Relationship questions","GraphRAG can help"],["Multi-hop questions","Graph and agentic approaches can help"],["Investigation questions","Agentic reasoning becomes valuable"]].map(([title,copy]) => <div key={title} className="bg-secondary p-5"><strong className="text-sm text-foreground">{title}</strong><p className="mt-3 text-xs leading-5 text-muted-foreground">{copy}</p></div>)}</div></section></PageShell>; }

function ComplexityBar({label,value,kind}:{label:string;value:number;kind:string}) { return <div className="grid grid-cols-[54px_1fr_32px] items-center gap-2 text-[10px] text-muted-foreground"><span>{label}</span><span className="h-1.5 bg-surface-strong"><span className={`block h-full ${kind === "cyan" ? "bg-cyan" : kind === "violet" ? "bg-violet" : "bg-primary"}`} style={{width:`${value}%`}} /></span><span>{value}%</span></div>; }